language: php
dist: trusty

notifications:
  email: false

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - PRODUCT_NAME=suite

    - php: 7.2
      env:
        - PRODUCT_NAME=b2c-demo-shop

    - php: 7.2
      env:
        - PRODUCT_NAME=b2b-demo-shop

services:
  - postgresql
  - redis-server
  - rabbitmq

addons:
  postgresql: "12"

  apt:
    packages:
      - graphviz
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - MODULE_DIR=module
    - SHOP_DIR=current
    - MODULE_NAME=computop
    - POSTGRES_PORT=5432

cache:
  directories:
    - $SHOP_DIR/current/vendor
    - $HOME/.composer/cache

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini

script:
  - git clone -b feature/eco-2952-psd2-notify-url-build https://github.com/spryker-eco/eco-ci.git ecoci
  - ./ecoci/build/travis.sh
